#!/usr/bin/env bash

if [ -n "${WA_CLI_DEBUG}" ]; then
  set -x
fi

COLOR_BLACK='\033[30m'
COLOR_RED='\033[31m'
COLOR_GREEN='\033[32m'
COLOR_YELLOW='\033[33m'
COLOR_BLUE='\033[34m'
COLOR_MAGENTA='\033[35m'
COLOR_CYAN='\033[36m'
COLOR_LIGHT_GRAY='\033[37m'
COLOR_DARK_GRAY='\033[38m'
COLOR_NORMAL='\033[39m'

bcli_trim_whitespace() {
  # Function courtesy of http://stackoverflow.com/a/3352015
  local var="$*"
  var="${var#"${var%%[![:space:]]*}"}"    # remove leading whitespace characters
  var="${var%"${var##*[![:space:]]}"}"    # remove trailing whitespace characters
  echo -n "$var"
}

bcli_show_header() {
  echo -e "$(bcli_trim_whitespace "$(cat "$1/.name")")"
  echo -e "${COLOR_CYAN}Version    ${COLOR_NORMAL}$(bcli_trim_whitespace "$(cat "$1/.version")")"
  echo -e "${COLOR_CYAN}Author     ${COLOR_NORMAL}$(bcli_trim_whitespace "$(cat "$1/.author")")"
}

wa_project_dir() {
  local PROJECT_DIR
  local INIT_DIR
  PROJECT_DIR=""
  INIT_DIR=$(pwd)
  while [ "${PWD}" != "/" ]; do
    if [ -e Dockerfile ]; then
      PROJECT_DIR=$(pwd)
      break
    else
      cd ..
    fi
  done
  cd "${INIT_DIR}" || return 1

  if [ -n "${PROJECT_DIR}" ]; then
    echo "${PROJECT_DIR}"
    return 0
  else
    echo "Please run this command from within a weahead project folder 🤦" >&2
    return 1
  fi
}

wa_dinghy_running() {
  if dinghy status | grep -iq "stopped"; then
    return 1
  fi
  return 0
}

wa_check_docker() {
  if hash dinghy 2>/dev/null; then
    if ! wa_dinghy_running; then
      dinghy down
      if ! dinghy up 1>/dev/null 2>&1; then
        if ! docker-machine start dinghy 1>/dev/null 2>&1; then
          echo "Failed to start Dinghy 😧" >&2
          echo "Try manually starting it and rerunning the command." >&2
          return 1
        fi
        dinghy down 1>/dev/null 2>&1
        dinghy up 1>/dev/null 2>&1
      fi
    fi
    eval "$(dinghy env)"
    if ! docker ps 1>/dev/null 2>&1; then
      echo "Failed to communicate with Docker daemon 😭" >&2
      return 1
    fi
  else
    echo "Could not find Dinghy, is it installed properly? 🤔" >&2
    return 1
  fi

  if wa_check_docker_login_to_gitlab; then
    return 0
  fi

  return 1
}

wa_check_docker_login_to_gitlab () {
  if ! grep -iq registry.gitlab.com ~/.docker/config.json; then
    warn "You are not authenticated to our registry over at GitLab.
If you already have a \"Personal Access Token\" for GitLab please provide it at the next password prompt.
If you do not have a \"Personal Access Token\" please go to https://gitlab.com/profile/personal_access_tokens and create one.
It is recommeded that you save it in your LastPass vault for future reference."
    info "Logging in to registry.gitlab.com
Please provide your username for gitlab.com and your \"Personal Access Token\" as the password."
    docker login registry.gitlab.com
  fi
}

wa_image_name () {
  local PROJECT_DIR
  PROJECT_DIR=$(wa_project_dir) || exit $?
  head -n 1 "${PROJECT_DIR}/Dockerfile" | sed 's/FROM //' | sed 's/:.*//'
}

wa_image_version () {
  local PROJECT_DIR
  PROJECT_DIR=$(wa_project_dir) || exit $?
  head -n 1 "${PROJECT_DIR}/Dockerfile" | sed 's/.*://'
}

wa_select_tag () {
  local IMAGE LABEL TAGS VERSION
  IMAGE="${1}"
  LABEL="${2}"

  TAGS=$(curl -sL "https://hub.docker.com/v2/repositories/weahead/${IMAGE}/tags/" 2>&1 | grep -Eo "\d+\.\d+\.\d+")
  if [ -n "${TAGS}" ]; then
    VERSION=$(wa_select "Select ${LABEL} version: " "${TAGS}")
  else
    warn "Failed to fetch tags from Docker hub. Please input ${LABEL} version manually" >&2
    VERSION=$(wa_input "${LABEL} version: ")
  fi

  echo "${VERSION}"
}

wa_set_tag () {
  local TAG
  TAG="${1}"

  if [ -n "${TAG}" ]; then
    sed -i '' -e "s/#TAG/${TAG}/g" Dockerfile
  else
    abort "Invalid value for tag
Aborting."
  fi
}

wa_ask () {
  # https://gist.github.com/davejamesmiller/1965569
  # https://djm.me/ask
  local prompt default reply question

  if [ -z "${1}" ]; then
    question="Are you sure you want to continue?"
  else
    question="${1}"
  fi

  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -en "${COLOR_YELLOW}${question} [${prompt}] ${COLOR_NORMAL}"

    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read -r reply </dev/tty

    # Empty line for spacing in output
    echo

    # Default?
    if [ -z "${reply}" ]; then
      reply=${default}
    fi

    # Check if the reply is valid
    case "${reply}" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}

wa_ask_yes () {
  wa_ask "${1}" Y
  return $?
}

wa_ask_no () {
  wa_ask "${1}" N
  return $?
}

wa_select () {
  # https://askubuntu.com/a/1716

  local title opt

  if [ -n "${1}" ]; then
    title="${1}"
  else
    title="Please select your choice: "
  fi
  PS3="${title}"
  select opt in ${2}
  do
    echo "${opt}"
    break;
  done
  PS3=""
}

wa_input () {
  local reply

  read -p "${1}" -r reply

  echo "${reply}"
}

abort () {
  if [ -n "${1}" ]; then
    err "${1}"
  else
    err "Aborting."
  fi
  exit 1
}

err () {
  echo -e "${COLOR_RED}"
  echo "${1}"
  echo -e "${COLOR_NORMAL}"
}

warn () {
  echo -e "${COLOR_YELLOW}"
  echo "${1}"
  echo -e "${COLOR_NORMAL}"
}

info () {
  echo -e "${COLOR_BLUE}"
  echo "${1}"
  echo -e "${COLOR_NORMAL}"
}

success () {
  echo -e "${COLOR_GREEN}"
  if [ -n "${1}" ]; then
    echo "${1}"
  else
    echo "Finished successfully"
  fi
  echo -e "${COLOR_NORMAL}"
}
