#!/usr/bin/env bash

set -e

trap ctrl_c INT

ctrl_c () {
  echo -e "${COLOR_NORMAL}"
  exit 1
}

ROOT_DIR=$(dirname "$(perl -e 'use Cwd "abs_path"; print abs_path(shift)' "$0")")

. "${ROOT_DIR}/../../utils"

confirmit () {
  if [ -n "${PREVIEW}" ]; then
    info "Command: $*"
    wa_ask_yes
  fi
}

runit () {
  confirmit "$@"
  $@
  return $?
}

wa_brew_install_or_upgrade () {
  local PACKAGE
  PACKAGE="${1}"

  if brew ls | grep -iq "${PACKAGE}"; then
    confirmit brew upgrade "${PACKAGE}"
    set +e
    UPGRADE_OUTPUT=$(brew upgrade "${PACKAGE}" 2>&1 > /dev/null)
    UPGRADE_EXIT_CODE=$?
    set -e
    if [ "${UPGRADE_EXIT_CODE}" -ne "0" ] && ! echo "${UPGRADE_OUTPUT}" | grep -iq "already installed"; then
      exit ${UPGRADE_EXIT_CODE}
    fi
  else
    runit brew install "${PACKAGE}"
  fi
}

# xhyve
wa_install_xhyve () {
  wa_brew_install_or_upgrade docker-machine-driver-xhyve
  runit sudo chown root:wheel "$(brew --prefix)"/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
  runit sudo chmod u+s "$(brew --prefix)"/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
}

# dinghy
wa_install_dinghy () {
  runit brew tap codekitchen/dinghy
  wa_brew_install_or_upgrade dinghy
}

# docker & friends
wa_install_docker_and_friends () {
  wa_brew_install_or_upgrade docker
  wa_brew_install_or_upgrade docker-machine
  wa_brew_install_or_upgrade docker-compose
}

# VM
wa_create_dinghy_vm () {
  local provider
  provider="${1}"
  runit dinghy create --cpus=1 --memory=2048 --provider="${provider}" --disk=51200
}


warn "#################################
### PLEASE READ THE FOLLOWING ###
#################################

This command will try and setup your development environment for We ahead.
It will primarily install Docker and the software needed to run it properly.
It will therefore make system changes and will probably prompt you for
your administrator password.

Please provide it if so 🙇

Press enter, when you have read the above

...or CTRL+C if you wish to abort."
read -r

if wa_ask_no "For your convenience, would you like to preview all commands before they are executed?
If so, type \"Y\", if not leave empty or type \"N\" and all commands will be executed without user confirmation."; then
  echo "Before a command is run it will be displayed, just press enter to execute it, or CTRL+C to abort."
  echo "Press enter when ready, and lets go for real! Promise! 🤞"
  read -r
  PREVIEW=1
else
  info "Executing all commands...please wait and enter your administrator password if asked to do so."
fi

brew update > /dev/null 2>&1

if hash VBoxManage 2>/dev/null; then
  VIRTUAL_BOX=1
fi

wa_install_docker_and_friends

if [ -z "${VIRTUAL_BOX}" ]; then
  wa_install_xhyve
fi
wa_install_dinghy

if ! docker-machine ls --filter "Name=dinghy" -q | grep -iq dinghy; then
  if [ -z "${VIRTUAL_BOX}" ]; then
    wa_create_dinghy_vm xhyve
  else
    wa_create_dinghy_vm virtualbox
  fi
fi

success "Setup was a success!"

info "Testing setup..."

"${ROOT_DIR}/../status"
