#!/usr/bin/env bash

ROOT_DIR=$(dirname "$(perl -e 'use Cwd "abs_path"; print abs_path(shift)' "$0")")

. "${ROOT_DIR}/../utils"

if wa_check_docker; then

    if wa_image_name | grep weahead\\/nodejs 1>/dev/null 2>&1; then
        "${ROOT_DIR}/npm/install"
    fi

    docker-compose build --pull && \
    "${ROOT_DIR}/down" && \
    docker-compose up "$@"
fi
